version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the pre_build phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
      - mkdir deploy
      - cp target/messageUtil-1.0.jar deploy/
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket cloudbuild-us-east-1-output-build --output-template-file NewSamTemplate.yaml
artifacts:
  type: zip
  files:
    - deploy/messageUtil-1.0.jar
    - NewSamTemplate.yaml
    - temp
