version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the pre_build phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
      - mvn package shade:shade
  post_build:
    commands:
      - echo Build completed on `date`
      - mkdir deploy
      - mkdir deploy/lib
      - cp target/userfilterlambda-4.0.0.jar deploy/lib
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket cloudbuild-us-east-1-output-build --output-template-file NewSamTemplate.yaml
artifacts:
  type: zip
  files:
    - deploy/lib/userfilterlambda-4.0.0.jar
    - NewSamTemplate.yaml
