AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  MeggageUtil:
    Type: AWS::Serverless::Function
    Properties:
      Handler: MessageUtil
      Runtime: java8
      CodeUri: target
      Role: 'arn:aws:iam::812618411163:role/cloudformation-lambda-execution-role'
            