AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  MeggageUtil:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: java8
      CodeUri: ./target
      Events:
        MeggageUtilApi:
          Type: Api
          Properties:
            Path: /MeggageUtilResource
            Method: GET