AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: User Filter 
Resources:
  UserFilter:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.amazonaws.lambda.userfilterlambda.stream.UserFilterStreamLambda
      Runtime: java8
      CodeUri: deploy
      Policies: AmazonDynamoDBReadOnlyAccess
      Events:
        MessageUtilApi:
          Type: Api
          Properties:
            Path: /userFilter
            Method: POST
        CheckWebsiteScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)          
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
       TableName: PUB_SUB
       AttributeDefinitions:
         - AttributeName: TENANTID_PERSONID
           AttributeType: B
         - AttributeName: TOPIC
           AttributeType: B
       KeySchema:
         - AttributeName: TENANTID_PERSONID
           KeyType: HASH
         - AttributeName: TOPIC
           KeyType: RANGE   
       ProvisionedThroughput:
         ReadCapacityUnits: 5
         WriteCapacityUnits: 5
       GlobalSecondaryIndexes:
        -
          IndexName: myGSI
          KeySchema:
            -
              AttributeName: TOPIC
              KeyType: HASH
            -
              AttributeName: TENANTID_PERSONID
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1  