AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  MessageUtil:
    Type: AWS::Serverless::Function
    Properties:
      Handler: MessageUtil
      Runtime: java8
      CodeUri: deploy
      Events:
        MessageUtilApi:
          Type: Api
          Properties:
            Path: /MessageUtilResource
            Method: GET
            